version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: nobarrier
    hostname: backend
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - postgres_db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
#    command: uvicorn src.nobarrier.main:app --host 0.0.0.0 --port 8000 --reload
    stdin_open: true  # Open StDIN for interactive sessions
    tty: true         # Turn on the terminal (optionally, convenient for iPython)
#    dns:
#      - 8.8.8.8
#      - 8.8.4.4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  migrations:
    build:
      context: .
      dockerfile: docker/migrations/Dockerfile
    container_name: nobarrier-migrations
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - postgres_db
    working_dir: /usr/src/app/nobarrier/database/migrations
    command: ["upgrade", "head"]
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  postgres_db:
#    build:
#      context: ./docker/postgresql
#      dockerfile: Dockerfile
    image: postgres:16
    container_name: nobarrier-pgsql-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
#      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./docker/nginx/html:/usr/share/nginx/html:ro  # for static files
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

volumes:
  postgres_data: